patch 970_sii902x_edid_readback_fix.patch
Patch backported with accommodations for MTK's CEC support patches.
This patch depends on 058_add_unlocked_i2c_smbus_xfer_variant.patch.

commit 21d808405fe49028036932dd969920f4fee4f481
Author: Fabrizio Castro <fabrizio.castro@bp.renesas.com>
Date:   Tue Nov 6 11:52:36 2018 +0000

    drm/bridge/sii902x: Fix EDID readback

    While adding SiI9022A support to the iwg23s board, it came
    up that when the HDMI transmitter is in pass through mode the
    device is not compliant with the I2C specification anymore,
    as it requires a far bigger tbuf, due to a delay the HDMI
    transmitter is adding when relaying the STOP condition on the
    monitor i2c side of things.

    When not providing an appropriate delay after the STOP condition
    the i2c bus would get stuck. Also, any other traffic on the bus
    while talking to the monitor may cause the transaction to fail
    or even cause issues with the i2c bus as well.

    I2c-gates seemed to reach consent as a possible way to address
    these issues, and as such this patch is implementing a solution
    based on that. Since others are clearly relying on the current
    implementation of the driver, this patch won't require any DT
    changes.

    Since we don't want any interference during the DDC Bus
    Request/Grant procedure and while talking to the monitor, we
    have to use the adapter locking primitives rather than the
    i2c-mux locking primitives.

    Signed-off-by: Fabrizio Castro <fabrizio.castro@bp.renesas.com>
    Reviewed-by: Peter Rosin <peda@axentia.se>
    Acked-by: Linus Walleij <linus.walleij@linaro.org>
    Tested-by: Yannick Fertré <yannick.fertre@st.com>
    Signed-off-by: Boris Brezillon <boris.brezillon@bootlin.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/1541505156-8097-1-git-send-email-fabrizio.castro@bp.renesas.com

commit ea6b13e9fed0fda9532ee04d38ed1bef1edbfdbf
Author: Fabrizio Castro <fabrizio.castro@bp.renesas.com>
Date:   Mon Nov 19 13:26:18 2018 +0000

    drm/bridge/sii902x: Add missing dependency on I2C_MUX

    kbuild test robot reports:

    >> ERROR: "i2c_mux_add_adapter" [drivers/gpu/drm/bridge/sii902x.ko] undefined!
    >> ERROR: "i2c_mux_alloc" [drivers/gpu/drm/bridge/sii902x.ko] undefined!
    >> ERROR: "i2c_mux_del_adapters" [drivers/gpu/drm/bridge/sii902x.ko] undefined!

    Quite obviously the driver depends on I2C_MUX, but adding a "depends on"
    introduces a recursive dependency, therefore this patch selects I2C_MUX
    instead.

    Fixes: 21d808405fe4 ("drm/bridge/sii902x: Fix EDID readback")
    Signed-off-by: Fabrizio Castro <fabrizio.castro@bp.renesas.com>
    Link: https://lists.01.org/pipermail/kbuild-all/2018-November/054924.html
    Acked-by: Peter Rosin <peda@axentia.se>
    Signed-off-by: Boris Brezillon <boris.brezillon@bootlin.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/1542633978-22064-1-git-send-email-fabrizio.castro@bp.renesas.com

commit bceee9bb894887ac38fae0f3f784dad4302114fd
Author: Jyri Sarha <jsarha@ti.com>
Date:   Mon May 27 16:47:53 2019 +0300

    drm/bridge: sii902x: Set output mode to HDMI or DVI according to EDID

    Set output mode to HDMI or DVI according to EDID HDMI signature.

    Signed-off-by: Jyri Sarha <jsarha@ti.com>
    Reviewed-by: Andrzej Hajda <a.hajda@samsung.com>
    Reviewed-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
    Signed-off-by: Andrzej Hajda <a.hajda@samsung.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/c42838073b83185a5cf9949caab3c70ee093b791.1558964241.git.jsarha@ti.com

diff -aurp -x '*.orig' linux-4.9.99-orig/drivers/gpu/drm/bridge/Kconfig linux-4.9.99/drivers/gpu/drm/bridge/Kconfig